# Generated by Django 5.2.9 on 2025-12-14 12:28

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="updated_date",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
